# Generated by Django 5.1.4 on 2025-01-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="first_name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.FileField(upload_to="data"),
        ),
    ]
