# Generated by Django 5.1.4 on 2025-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name_plural": "Review's"},
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
